name: Render Spring Boot Deployment

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
